const currentImg=document.querySelector("#currentImg");const strapImgDiv=document.querySelectorAll(".strapImgDiv img");let currentImgIndex=1;let opacity=0.6;strapImgDiv[0].style.opacity=opacity;strapImgDiv.forEach(img=>img.addEventListener('click',imgClick));function imgClick(e){strapImgDiv.forEach(img=>img.style.opacity=1);currentImg.src=e.target.src;currentImg.classList.add('fade-in');currentImgIndex=parseInt(e.target.id);setTimeout(()=>currentImg.classList.remove('fade-in'),500);e.target.style.opacity=opacity}
document.addEventListener("keyup",function(e){if(e.keyCode===39){nextImg(e)}})
document.addEventListener("keyup",function(e){if(e.keyCode===37){prevImg(e)}})
function nextImg(){if(document.getElementById(currentImgIndex+1)!==null){currentImgIndex+=1}else{currentImgIndex=1;strapImgDiv[0].style.opacity=opacity}
strapImgDiv.forEach(img=>img.style.opacity=1);currentImg.src=document.getElementById(currentImgIndex).src;currentImg.classList.add('fade-in');setTimeout(()=>currentImg.classList.remove('fade-in'),500);document.getElementById(currentImgIndex).style.opacity=opacity}
function prevImg(){if(document.getElementById(currentImgIndex-1)!==null){currentImgIndex-=1}else{nbImg=document.querySelectorAll(".strapPageImg").length;currentImgIndex=nbImg}
strapImgDiv.forEach(img=>img.style.opacity=1);currentImg.src=document.getElementById(currentImgIndex).src;currentImg.classList.add('fade-in');setTimeout(()=>currentImg.classList.remove('fade-in'),500);document.getElementById(currentImgIndex).style.opacity=opacity}
currentImg.addEventListener('click',function(e){nextImg(e)})
let listener=SwipeListener(currentImg);currentImg.addEventListener('swipe',function(e){let directions=e.detail.directions;if(directions.left){if(document.getElementById(currentImgIndex+1)!==null){currentImgIndex+=1}else{currentImgIndex=1;strapImgDiv[0].style.opacity=opacity}
strapImgDiv.forEach(img=>img.style.opacity=1);currentImg.src=document.getElementById(currentImgIndex).src;currentImg.classList.add('fade-in');setTimeout(()=>currentImg.classList.remove('fade-in'),500);document.getElementById(currentImgIndex).style.opacity=opacity}
if(directions.right){if(document.getElementById(currentImgIndex-1)!==null){currentImgIndex-=1}else{nbImg=document.querySelectorAll(".strapPageImg").length;currentImgIndex=nbImg}
strapImgDiv.forEach(img=>img.style.opacity=1);currentImg.src=document.getElementById(currentImgIndex).src;currentImg.classList.add('fade-in');setTimeout(()=>currentImg.classList.remove('fade-in'),500);document.getElementById(currentImgIndex).style.opacity=opacity}})